The following error occurs on EAP once make the rest-binding qs as a OSGi bundle. This happens when executing mvn exec:java -Dexec.args="add 1 3 10" after mvn exec:java -Dexec.args="new".
org.switchyard.SwitchYardException: SWITCHYARD010813: Cannot convert from 'org.jboss.resteasy.client.core.BaseClientResponse' to 'org.switchyard.quickstarts.rest.binding.Item'.  No registered Transformer available for transforming from 'java:org.jboss.resteasy.client.core.BaseClientResponse' to 'java:org.switchyard.quickstarts.rest.binding.Item'.  A Transformer must be registered.